### ISSUE TITLE
Configurar splash screen.

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-react#26]

**Comment by sebastiancesar** [comment]
Que sería mejorar la splash? Que hay que mostrar?

**Comment by Epotignano** [comment]
Mostrar, no mejorar, seria poner un splash screen, ya te paso la url de la imágen que debería ir

**Comment by Epotignano** [comment]
http://res.cloudinary.com/ceiboit/image/upload/v1452990023/imgpsh_fullsize_m24pha.jpg
