### ISSUE TITLE
Buildear IOS

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-react#27]

**Comment by sebastiancesar** [comment]
Tomado. Ya estoy hacinedo una build para ios, salen bugs en la app, estoy tratando de juntar info para postear el issue

**Comment by Epotignano** [comment]
Quedó?

**Comment by sebastiancesar** [comment]
Si, ya hay una versión subida al testflight, las próximas versiones van a ir saliendo por ahí.
