### ISSUE TITLE
Android: No se carga la landing

### ISSUE THREAD

**Issue by sebastiancesar** [CeiboIT/sof-tokyo-react#39]
Buildea la apk para release, encontré lo siguiente, que no se si son bugs:

1) Me aparece un cartel amarillo con warnings:
  toRoute, customAction
  SyntaxError: JSON Parse error: Unrecognized token '<'
(captura 1)

2) Queda un texto que dice :
 "Dos amante que seentrega la piel"  
mmmmmmmm, que onda eso?

3) Cuando hago swipe de izquierda a derecha, para hacer aparecer la pantalla de login, según donde suelte el swipe, se queda clavada la pantalla (captura 2)

![captura-1](https://cloud.githubusercontent.com/assets/5677646/12430131/b368f1ac-becc-11e5-94f2-ac36d005f141.png)
![captura-2](https://cloud.githubusercontent.com/assets/5677646/12430130/b365f0a6-becc-11e5-8d35-e459a42bc371.png)

**Comment by Epotignano** [comment]
jajajajajajajajajajajjajajajajajajjajaa!!!! Anda lento esa chota!  proque
estamos trayendo 15 posts!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by jlmosconi** [comment]
Jajajajajajajajaja, es la que va

**Comment by Epotignano** [comment]
Siendo un poco mas serios, eso de que se queda clavada, es un bardo del
simulator, en el telefono no me paso nunca.

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by Epotignano** [comment]
Todas esas frases locas son obras del "Timbalero" un personaje grotesco de
la ciudad bolivarense, cosas del campo vio.

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by sebastiancesar** [comment]
el Timbalero, con ese nombre no se que esperarme!.

Las capturas son desde la tablet, pase del largo el simulador así ya voy probando como funciona el buildeo de apks firmada. Ese es una lista para salir a release de play store, pero a tener en cuenta quien la firma, porque una vez firmada, creo que hay que usar siempre la misma firma.
