### ISSUE TITLE
Permitir cargar fotos a cloudinary.

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-react#46]
Te veo en esta integracion a vos seba!
El usuario debe poder seleccionar una foto de su telefono, enviarla y que esta foto se cargue, luego con la url obtenida, debe poder incluirla en los datos que envia a la api ya sea para crear o updatear un post.

**Comment by sebastiancesar** [comment]
La primera parte de la tarea está, que es tomar las imagenes desde la galeria del dispositivo.
La segunda parte, es subirla a cloudinary, y se me está complicando por lo siguiente:

Según la doc, se puede hacer un posteo directo por url a cloudinary, subiendo la imagen. Para ese posteo, hay que hacerlo desde un form de los de html, y dentro de react no hay ese form, porque no tiene dom, las alternativas son usar jquery pero estamos en la misma, no hay dom.

Luego, hay sdks para android y ios, pero no para reactive en particular, por lo que hay que ponerse a escribir los bridges a manopla para las dos plataformas.

La opción que por ahora veo mas viable, es usar la sdk que tienen para nodejs, agregar ese módulo al backend en node que ya tiene softokyo y que la app mobile le pegue directamente a nuestro backend, y que desde el backend se suba a cloudinary. Así que voy a ir por esta vía.

**Comment by Epotignano** [comment]
Me parece super coherente!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.
