### ISSUE TITLE
Se rompe el build - master

### ISSUE THREAD

**Issue by sebastiancesar** [CeiboIT/sof-tokyo-react#50]
Sale error con CommentIte
![screenshot_2016-01-23-20-18-21](https://cloud.githubusercontent.com/assets/5677646/12533522/7ecc84bc-c210-11e5-933e-a002a5cf60b2.png)

**Comment by Epotignano** [comment]
No me esta pasando, debe ser alguna referencia mal hecha. Ocurre algo como minificación o algo similar para saber que puede ser?

**Comment by Epotignano** [comment]
Novedades de esto?

**Comment by sebastiancesar** [comment]
Me mataste, creerí que si, lo minifica, lo que hice fué
un pull master 
react-native run-android
react-native start

ahí me lo levantó en la app del teléfono y me tiró ese cartel. 
Vos como corres la app?

**Comment by Epotignano** [comment]
Igual, pero en el simulador! y no me pasa nada!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-01-24 10:12 GMT-03:00 Sebastian Fondra notifications@github.com:

**Comment by sebastiancesar** [comment]
Prece que falta un archivo, en PostViews.js se hace un 
var CommentInput = require("../components/posts/helpers/CommentInput")

Pero ese CommentInput no existe ahí, capaz que lo tenés local, pero no está comiteado

**Comment by Epotignano** [comment]
Ahhhhh que idiota! Claro si!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-01-24 12:12 GMT-03:00 Sebastian Fondra notifications@github.com:

**Comment by Epotignano** [comment]
Sacalo un toquecito, que eso lo tengo que terminar bien del todo de mi
lado, tengo que hacer un par de merges. saquele ese require que se me escapo

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by Epotignano** [comment]
Fixed en el ultimo commit
