### ISSUE TITLE
Permitir registro de usuario con los mismos datos que puede encontrarse en la web de sofTokyo

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-react#62]
Mirar los datos que pide http://sof.tokyo/register/

**Comment by Epotignano** [comment]
Seba o jose, el que llegue primero

**Comment by sebastiancesar** [comment]
La herramienta que se está usando para formularios en react native parece tener soporte para ios nada mas (tcomb-react-form).
Hay que hacer los formularios a mano.

**Comment by sebastiancesar** [comment]
Tampoco el react 0.17 tiene el Picker implementado para android, y ahí no se como hacer para  mostrarle un select al usuario y que elija la afiliation. Al horno el react para android.

**Comment by Epotignano** [comment]
Desgracia que hemos escuchado! XD
El problem es los campos que tienen un select adentro, eso lo tneia
identificado, perdon por no documentarlo.
Para todos los demás campos, no hay drama.

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-02-08 17:58 GMT-03:00 Sebastian Fondra notifications@github.com:

**Comment by Epotignano** [comment]
Si, fijate, yo resolvi, directamente mostrar un menu con varios elementos,
no nos queda otra xD
O sea, mostrar una lista y que escoja un elemento, otra no se me ocurre

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-02-08 19:01 GMT-03:00 Sebastian Fondra notifications@github.com:

**Comment by Epotignano** [comment]
0.18 tampoco implementa eso!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by sebastiancesar** [comment]
Una vez que el usuario envio los datos de registro, hace falta que confirme el registro por mail?

**Comment by Epotignano** [comment]
Esa funcionalidad ya existe esta implementada en wordpress, pero no se si
aplica que nosotros nos pongamos a chequear eso en la app mobile, que
opinás?

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-02-11 12:43 GMT-03:00 Sebastian Fondra notifications@github.com:

**Comment by sebastiancesar** [comment]
para saber que hacer con el usuario, si avisarle que tienen que ir a revisar el mail para completar el register, o mandarlo directamente a la pantalla de login.

**Comment by sebastiancesar** [comment]
probé con tcomb pero tenía el problema de que se me refrescaba toda la página cuando se oculta el teclado, probé con gifted y no entiendo como usarlo, la doc es bastante flaca, así que voy por inputs a mano, los que trae react.

**Comment by sebastiancesar** [comment]
Según el flujo actual de registro de usuarios, no podemos registranos directos, sino que primero hay abrir el mail donde llega el link de verificación, y luego ir al sitio de sof.tokyo para crear una contraseña. Es decir, el registro sigue dependiendo del sitio de sof.tokyo y de wordpress. Entonces, para esta etapa, podemos ofrecer la posibilidad de registrar usuario, pero no es directa la registración. 
Como para que el cliente vea que esta esa opción. Quedan pendiente issues (y bugs tal vez) sobre esta funcionalidad que los cargo aparte
