### ISSUE TITLE
Pantalla de Login - feedback al usuario

### ISSUE THREAD

**Issue by sebastiancesar** [CeiboIT/sof-tokyo-react#67]
Cuando se loguea, hay que informale al usuario  cuando no se pudo loguear, si fué por error en el servidor, por ingresar mal contraseña/usuario, o por campos incompletos.

**Comment by Epotignano** [comment]
Genial, armo esas traducciones asi las metemos ahi, viste el componente de
i18n?

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by sebastiancesar** [comment]
Si, vengo usandolo, pero no vi que haya cargado ningún texto todavía.

**Comment by Epotignano** [comment]
Hay varios textos con eso ya!

**Comment by sebastiancesar** [comment]
Esta tarea quedó metida junto con la de register, que también necesitaba feedback al usuario por errores.
De login, el mensajes de error posible es:
.        'error_login_100': 'Username or password invalid'

**Comment by Epotignano** [comment]
Eso dejalo pintado con i18n que yo paso despues con las traducciones.

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-02-16 17:41 GMT-03:00 Sebastian Fondra notifications@github.com:
