### ISSUE TITLE
Registro de usuarios: faltan campos (no obligatorios)

### ISSUE THREAD

**Issue by sebastiancesar** [CeiboIT/sof-tokyo-react#69]
Permitir al usuario cargar school, country y ob al momento de registrarse.
El campo country es recortado, no son todos los paises, sino un campo con :
[Japan, Euro, US, Other]

El campo Ob tiene dos opciones,
[Ob, Og]

El campo school tiene un listado de schools/affiliaciones que tiene que ser cargado desde el backend. No encontré ese endpoint, hay que pedirlo a Mati

**Comment by Epotignano** [comment]
Ese endpoint existe.
De hecho esta dentro de la app de React.
ya te paso el dato.

**Comment by Epotignano** [comment]
sof-tokyo-react/app/utils/api/SchoolsApi.js

Ahi está, es la única función que hay hoy.

**Comment by sebastiancesar** [comment]
Subo lo que está hecho a master, para ver si con estilos mejora la cosa.
