### ISSUE TITLE
Registro de usuarios: Estilos

### ISSUE THREAD

**Issue by sebastiancesar** [CeiboIT/sof-tokyo-react#70]
El formulario de registro tiene otro estilo diferente comparado al formulario de login, llevar a uno solo estilo.

**Comment by Epotignano** [comment]
Genial! lo mandamos al jose! Crees que llegamos a meter Facebook? Solo para saber, si no entra, no entra.

**Comment by sebastiancesar** [comment]
Creo debe llevar su tiempo, primero sacaría los prioritarios que tenemos y ahí lo estimamos.  Si se registra con fb, igual tiene que entrar al sitio a terminar de completar los datos del register, me imagino que debe llevar 3 dias como mínimo.

**Comment by Epotignano** [comment]
Listo, olvidemoslo entonces.
