### ISSUE TITLE
Vista de Creación / Edición de posts

### ISSUE THREAD

**Issue by Epotignano** [CeiboIT/sof-tokyo-react#79]
Necesitamos crear una vista al igual que la que existe en sof.tokyo, podemos omitir algunos campos que no veamos necesarios si fueran demasiado molestos.

Para acceder a sof.tokyo, ingresar en login epotignano como username y pass 5772123a

**Comment by sebastiancesar** [comment]
Tomo la tarea. En la vista de creación hay varios campos, no se cuales son requeridos y cuales no, molestos van a ser todos, porque en la vista de un teléfono, mas que titulo, descripción y una foto ya se vuelve insoportable.

Son 15 campos que tiene que ingresar para crear un post, me parecen demasiados para hacerlo desde el teléfono, tiene que cargar imagen principal, y después cargar imagenes adicionales, 
Tiene 3 campos donde hay que presentarle al usuario muchas opciones, que en el teléfono ese listado se va a ver aspero.

Hacer todo eso va a llevar mas de una semana, como mínimo. Me parece que tenemos que definir cuales son los campos indispensables para crear un post si queremos mostrar algo en breve. 
Empezando por saber cuales son obligatorios para que wordpress te lo deje pasar.

**Comment by Epotignano** [comment]
Genial, definamos

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.
