### ISSUE TITLE
Generar builds ios/android

### ISSUE THREAD

**Issue by sebastiancesar** [CeiboIT/sof-tokyo-react#82]
Generar una build para ambas plataformas y subirlas

**Comment by sebastiancesar** [comment]
Algo pasó con ios que no puedo buildear, me patea porque no encuentra un certificado, lo cual es raro porque no toque nada de ceritificados y venía buildenado lo mas bien. Que vuelteros que son por favor.

**Comment by sebastiancesar** [comment]
Otra hermosura de apple, que me rompio la cabeza hace horas

... The previous Apple Worldwide Developer Relations Certification Intermediate Certificate expired on February 14, 2016 and the renewed certificate must now be used when signing...

Se vencio un certificado (a todo el mundo) el 14 de febrero, y a todo el mundo que no se enteró de eso, le está pasando lo mismo. 
Solucionado bajando el neuvo certificado, que expira en el 2023.
Lo malo es que no te decía que era un certificado de Apple lo que fallaba, sino que eran tus certificados los que estaban mal, podría haber hecho un mensaje de error mas coherente.

**Comment by Epotignano** [comment]
Hermoso!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.
