### ISSUE TITLE
Sacar el texto "opcional" de la pantalla de búsqueda.

### ISSUE THREAD

**Issue by sebastiancesar** [CeiboIT/sof-tokyo-react#85]
Quedó el label la palabra "opcional" en la pantalla de búsqueda, y de paso, no me funcionó la busqueda. ¿Eso está andando?

**Comment by Epotignano** [comment]
Ese texto lo saqué, en master no debería estar

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

**Comment by sebastiancesar** [comment]
Por lo que entiendo, el texto aparece de manera automática, lo pone el tcomb, para los campos opcionales. En master es donde lo ví. En el código, por lo menos en la pantalla de search, no encontré referencias de que se fuera ese texto.
Lo que hice fué agregar esto a search.js

t.form.Form.i18n = {
    optional: '(任意)',
    required: ' ' 
};

**Comment by Epotignano** [comment]
Ahi subo eso tambien!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.
